import re

with open("gr-techniquemaker/lib/interdictor_cpp_impl.cc", "r") as f:
    content = f.read()

# Find start of generate_cw_tone
start_idx = content.find("void interdictor_cpp_impl::generate_cw_tone()")

# Find start of perform_spectral_detection
end_idx = content.find("void interdictor_cpp_impl::perform_spectral_detection()")

new_code = """void interdictor_cpp_impl::set_base_waveform(const std::vector<std::complex<float>>& waveform)
{
    if (waveform.empty()) {
        d_base_waveform.assign(1, std::complex<float>(0,0));
    } else {
        d_base_waveform = waveform;
    }
    d_waveform_idx = 0;
}

"""

if start_idx != -1 and end_idx != -1:
    new_content = content[:start_idx] + new_code + content[end_idx:]
    
    # Now replace update_waveform
    update_start = new_content.find("void interdictor_cpp_impl::update_waveform()")
    update_end = new_content.find("// Setters", update_start)
    
    new_update = """void interdictor_cpp_impl::update_waveform()
{
    // The waveform is now generated by the Python UI and passed in via set_base_waveform
    d_waveform_idx = 0;
}

"""
    final_content = new_content[:update_start] + new_update + new_content[update_end:]
    
    with open("gr-techniquemaker/lib/interdictor_cpp_impl.cc", "w") as f:
        f.write(final_content)
    print("SUCCESS")
else:
    print("COULD NOT FIND INDICES")
